"""Provider-independent contracts, failover, model pool, and cooldown tracking for the reusable LLM gateway boundary."""

from gateway.llm_gateway.contracts import (
    APIError,
    AuthenticationError,
    BaseProvider,
    InvalidResponseError,
    LLMUnavailableError,
    LLMResponse,
    LLMStreamChunk,
    ProviderError,
    RateLimitError,
    RecoverableError,
    build_user_content,
)
from gateway.llm_gateway.provider_manager import (
    ProviderManager,
    _is_image_error,
    _is_image_error_response,
)
from gateway.llm_gateway.model_pool import (
    ModelPoolManager,
    ModelCatalogError,
    NoFreeModelsError,
    curate_models,
    build_curated_pool,
    UNSUITABLE_MODEL_TOKENS,
    _model_slug,
)
from gateway.llm_gateway.cooldown import (
    CooldownTracker,
    DEFAULT_COOLDOWN_SECONDS,
)
from gateway.llm_gateway.failure_policy import (
    COOLDOWN,
    DEAD,
    FATAL,
    ROTATE,
    _MODEL_UNAVAILABLE_MARKERS,
    _MODEL_UNAVAILABLE_PATTERN,
    classify_failure,
    classify_opencode_failure,
)
from gateway.llm_gateway.catalog import (
    DEFAULT_CACHE_TTL_SECONDS,
    DEFAULT_CATALOG_TIMEOUT_SECONDS,
    MODELS_DEV_URL,
    ModelsDevCatalog,
    ModelsDevCatalogError,
    _CatalogEntry,
    _is_free_cost,
    get_shared_catalog,
    parse_provider_free_models,
)

__all__ = [
    "APIError",
    "AuthenticationError",
    "BaseProvider",
    "InvalidResponseError",
    "LLMUnavailableError",
    "LLMResponse",
    "LLMStreamChunk",
    "ProviderError",
    "RateLimitError",
    "RecoverableError",
    "build_user_content",
    "ProviderManager",
    "_is_image_error",
    "_is_image_error_response",
    "ModelPoolManager",
    "ModelCatalogError",
    "NoFreeModelsError",
    "curate_models",
    "build_curated_pool",
    "UNSUITABLE_MODEL_TOKENS",
    "_model_slug",
    "CooldownTracker",
    "DEFAULT_COOLDOWN_SECONDS",
    "COOLDOWN",
    "DEAD",
    "FATAL",
    "ROTATE",
    "_MODEL_UNAVAILABLE_MARKERS",
    "_MODEL_UNAVAILABLE_PATTERN",
    "classify_failure",
    "classify_opencode_failure",
    "MODELS_DEV_URL",
    "DEFAULT_CACHE_TTL_SECONDS",
    "DEFAULT_CATALOG_TIMEOUT_SECONDS",
    "ModelsDevCatalog",
    "ModelsDevCatalogError",
    "_CatalogEntry",
    "_is_free_cost",
    "parse_provider_free_models",
    "get_shared_catalog",
]