"""add user authentication fields

Revision ID: 081ffd9766a9
Revises: 111bedfdea17
Create Date: 2026-08-13 16:05:00.457844+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081ffd9766a9'
down_revision: Union[str, None] = '111bedfdea17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration.

    The new columns are added as nullable and then backfilled for any
    pre-existing users, because adding ``NOT NULL`` columns directly to a
    populated ``users`` table would fail without a default value. After every
    existing row holds a valid value, the ``NOT NULL`` constraints are
    enforced with ``batch_alter_table``, which applies the constraint directly
    on PostgreSQL and recreates the table on backends that cannot alter column
    nullability in place.
    """
    op.add_column(
        'users',
        sa.Column('password_hash', sa.String(length=255), nullable=True),
    )
    op.add_column(
        'users',
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        'users',
        sa.Column('is_active', sa.Boolean(), nullable=True),
    )

    # Backfill existing rows with valid values. The updated_at default is
    # the row's created_at, since the column did not exist before.
    op.execute("UPDATE users SET password_hash = '' WHERE password_hash IS NULL")
    op.execute("UPDATE users SET updated_at = created_at WHERE updated_at IS NULL")
    op.execute("UPDATE users SET is_active = true WHERE is_active IS NULL")

    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('password_hash', nullable=False)
        batch_op.alter_column('updated_at', nullable=False)
        batch_op.alter_column('is_active', nullable=False)


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
